#!/usr/bin/env python3
"""Generate the tool-layer permission deny lists from `aios/config.yml` (M2-03).

PROVISIONAL. Becomes `aios generate deny-lists` when the binary exists (ADR-006).

One list is the source. `deny_commands` in the config holds regexes, which is what the hook
at aios/bin/hooks/deny-commands.py evaluates and what the 80 cases in tests/ cover. Claude
Code's `permissions.deny` is prefix-matched and cannot express most of them, so the config
declares the coarse form beside each regex and this script assembles the file. Nothing here
infers a prefix from a pattern: a generator guessing at regex semantics would produce entries
that look like coverage and match nothing.

Cursor gets no generated artifact, because it has no repo-level deny list to generate into
(ADR-012). It gets the hook, which is the same regexes.

  (no arguments)   check the checked-in files match what this would write; exit 1 if not
  --write          rewrite them

`--write` is a separate mode so that CI can run the check without the ability to make itself
pass, which is the whole point of a generated file being checked in.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from aios_state import CouldNotRun, find_config, load_config

PASS, DRIFTED, COULD_NOT_RUN = 0, 1, 2

GENERATED = ".claude/settings.json"


def deny_array(config: dict) -> tuple[list[str], list[str]]:
    """Return the deny entries, and the patterns no prefix could express.

    The second half is not a diagnostic. It is written into the generated file, because the
    difference in coverage between a regex layer and a prefix layer is a property of the
    system that someone reading either file should not have to derive by comparing them.
    """
    regexes = config.get("deny_commands") or []
    prefixes = config.get("deny_command_prefixes") or {}
    reads = config.get("deny_reads") or []

    missing = [rx for rx in regexes if rx not in prefixes]
    if missing:
        raise CouldNotRun(
            f"{len(missing)} deny_commands entries have no entry in deny_command_prefixes, "
            f"starting with {missing[0]!r}. Declare the coarse form, or declare an empty list "
            f"to say plainly that no prefix expresses it. What is not allowed is leaving it "
            f"out, because then the prefix-matched tool is quietly missing a rule the regex "
            f"tool has.")
    orphans = [rx for rx in prefixes if rx not in regexes]
    if orphans:
        raise CouldNotRun(
            f"{len(orphans)} deny_command_prefixes entries name a pattern that is no longer in "
            f"deny_commands, starting with {orphans[0]!r}. A widening of a rule that was "
            f"deleted is a rule nobody decided to have.")

    entries: list[str] = []
    unexpressible: list[str] = []
    for rx in regexes:
        coarse = prefixes[rx]
        if not coarse:
            unexpressible.append(rx)
            continue
        for prefix in coarse:
            entry = f"Bash({prefix})"
            if entry not in entries:  # several regexes widen to one prefix; say it once
                entries.append(entry)
    entries.extend(f"Read({path})" for path in reads)
    return entries, unexpressible


def rendered(root: Path, config: dict) -> str:
    """The full settings file, with only the deny array replaced.

    Everything else in that file — the hook registrations, the comment — is hand-written and
    stays hand-written. Generating the whole file would mean this script owned decisions it
    has no information about.
    """
    path = root / GENERATED
    try:
        current = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise CouldNotRun(f"{GENERATED} is not readable as JSON: {exc}")

    entries, unexpressible = deny_array(config)
    current.setdefault("permissions", {})["deny"] = entries
    current["permissions"]["_deny_is_generated"] = [
        "Generated by .github/scripts/generate-deny-lists.py from deny_commands and",
        "deny_command_prefixes in aios/config.yml. Edits here are overwritten; CI fails while",
        "this and the config disagree. The regexes run as a hook (preToolUse, Bash); this",
        "array is the prefix-matched floor beneath it.",
        f"{len(unexpressible)} of {len(config.get('deny_commands') or [])} patterns have no "
        f"prefix form and are enforced only by the hook:",
        *sorted(unexpressible),
    ]
    return json.dumps(current, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite the generated files")
    args = parser.parse_args()

    try:
        # The config's own location is the root, which is how every other gate here finds it.
        root = find_config().parent.parent
        text = rendered(root, load_config())
    except CouldNotRun as exc:
        print(f"could not run: {exc}", file=sys.stderr)
        return COULD_NOT_RUN

    path = root / GENERATED
    if args.write:
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {GENERATED}")
        return PASS

    if path.read_text(encoding="utf-8").replace("\r\n", "\n") == text:
        print(f"{GENERATED} matches aios/config.yml.")
        return PASS

    print(f"{GENERATED} does not match what aios/config.yml says it should be.\n"
          f"The deny list is generated. Run:\n"
          f"    python .github/scripts/generate-deny-lists.py --write\n"
          f"and commit the result. If you edited the settings file directly, move the change "
          f"into the config — this file is not where that decision lives.", file=sys.stderr)
    return DRIFTED


if __name__ == "__main__":
    raise SystemExit(main())
